# Generated by Django 5.1.1 on 2024-11-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_image_title_alter_projectdetail_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='media.team'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='media.projectdetail')),
            ],
        ),
    ]
