# Generated by Django 5.1.1 on 2024-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_image_title_team_team_image_alter_projectdetail_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
