# Generated by Django 5.1.1 on 2024-11-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_image_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='team_name',
        ),
    ]
