name: Deploy to AWS EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2  # 리전은 EC2 인스턴스에 맞게 설정

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: "ubuntu"
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd Click_BE 
            git pull origin main
            source venv/bin/activate 
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            uwsgi --ini uwsgi.ini
            sudo systemctl restart nginx 
          EOF
